author: rosu # 作者
description: rosu's blog
keyword: android, rosuh
favicon: /images/icon.png

excerpt_link: 「阅读更多」

menu:
 Home: /
 标签: /tags/
 归档: /archives/
 项目: /project/
 关于我: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: true

# qrcode
qrcode: true

# comment
# you can set gitment, uyan or disqus

comment: disqus

# gitment config
gitment_owner: 
gitment_repo: 
gitment_oauth_id: 
gitment_oauth_secret: 

# uyan config
# if you want to use uyan as your blog comment, plz remove/comment out gitment config
baidu_id: 

# disqus config
disqus_shortname: blog-rosuh-me

about: 
  banner: https://img.ioioi.top/personal/3431596.jpg
  avatar: https://img.ioioi.top/personal/author_logo.png
  description: "『任何足夠先進的科技，皆與魔法無異』"
  weibo_username: 
  twitter_username: rosu_h
  github_username: rosuH
  zhihu_username: 
  douban_username: 
  linkedin_username:

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML
